contact_links:
  - name: Mobileread Sigil User's Forum
    url: https://www.mobileread.com/forums/forumdisplay.php?f=203
    about: Please direct all new feature requests to our Sigil Forum on www.mobileread.com.  New feature requests are not accepted on our github site and they placed there will be immediately closed.
